@FirstProject_HostAddress = http://localhost:5179
@id=685aba262b4873617d2399ac
GET {{FirstProject_HostAddress}}/api/todoitems

###

POST {{FirstProject_HostAddress}}/api/todoitems
Content-Type: application/json

{
  "title": "Sample Todo Item",
  "isComplete": false
}

###

GET {{FirstProject_HostAddress}}/api/todoitems/{{id}}

###

PUT {{FirstProject_HostAddress}}/api/todoitems/{{id}}
Content-Type: application/json

{
  "id": "684b52338054ba3536ec062b",
  "title": "Uptadet Todo Item",
  "isComplete": true
}

###

DELETE {{FirstProject_HostAddress}}/api/todoitems/{{id}}

###

GET {{FirstProject_HostAddress}}/api/user

###

POST {{FirstProject_HostAddress}}/api/user
Content-Type: application/json

{
    "Name": "Reza",
    "Email": "reza@mail.com",
    "Password": "123"
}

###

PUT {{FirstProject_HostAddress}}/api/user/{{id}}/name
Content-Type: application/json

{
    "Name": "Reza Updated"
}

###
