@FirstProject_HostAddress = http://localhost:5179
@id=684b45a3ab77fcc31150eb6a
GET {{FirstProject_HostAddress}}/api/todoitems

###

POST {{FirstProject_HostAddress}}/api/todoitems
Content-Type: application/json

{
  "title": "Sample Todo Item",
  "isComplete": false
}

###

GET {{FirstProject_HostAddress}}/api/todoitems/{{id}}

###

PUT {{FirstProject_HostAddress}}/api/todoitems/{{id}}
Content-Type: application/json

{
  "id": "684b52338054ba3536ec062b",
  "title": "Uptadet Todo Item",
  "isComplete": true
}

###

DELETE {{FirstProject_HostAddress}}/api/todoitems/{{id}}

###
