@FirstProject_HostAddress = http://localhost:5179
@id=685ab385375f9be32ea3fabc
GET {{FirstProject_HostAddress}}/api/todoitems

###

POST {{FirstProject_HostAddress}}/api/todoitems
Content-Type: application/json

{
  "title": "Sample Todo Item",
  "isComplete": false
}

###

GET {{FirstProject_HostAddress}}/api/todoitems/{{id}}

###

PUT {{FirstProject_HostAddress}}/api/todoitems/{{id}}
Content-Type: application/json

{
  "id": "685ab385375f9be32ea3fabc",
  "title": "Uptadet Todo Item",
  "isComplete": true
}

###

DELETE {{FirstProject_HostAddress}}/api/todoitems/{{id}}

###

GET {{FirstProject_HostAddress}}/api/user

###

POST {{FirstProject_HostAddress}}/api/user
Content-Type: application/json

{
    "Name": "Reza",
    "Email": "rezaaa@mail.com",
    "Password": "123"
}

###

PUT {{FirstProject_HostAddress}}/api/user/{{id}}/name
Content-Type: application/json

{
    "Name": "Reza Updated"
}

###

POST {{FirstProject_HostAddress}}/api/auth/login
Content-Type: application/json

{
    "Email": "rezaaa@mail.com",
    "Password": "123"
}

###

POST {{FirstProject_HostAddress}}/api/auth/register
Content-Type: application/json

{
    "Name": "Reza",
    "Email": "reza@mail.com",
    "Password": "123"
}

###
